-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 010 — PIN auth + operational user management
-- Depends on: 001_initial_schema.sql, 009_billing_flow_extensions.sql
-- Purpose:
--   - Store technician/contractor PINs as one-way hashes.
--   - Add simple login codes for field PIN login.
--   - Track trusted devices after the first online PIN login.
--   - Keep admin-managed operational users editable without exposing PINs.
-- Run manually in Supabase SQL Editor.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS pin_login_code TEXT,
  ADD COLUMN IF NOT EXISTS pin_hash TEXT,
  ADD COLUMN IF NOT EXISTS pin_set_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_pin_login_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_pin_login_code
  ON public.profiles (lower(pin_login_code))
  WHERE pin_login_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_active_role
  ON public.profiles (role, is_active);

COMMENT ON COLUMN public.profiles.pin_login_code IS
  'Short field-login code used with a PIN. Case-insensitive unique when present.';

COMMENT ON COLUMN public.profiles.pin_hash IS
  'One-way PBKDF2 hash generated by Edge Functions. Never expose to frontend clients.';

REVOKE SELECT (pin_hash) ON public.profiles FROM anon, authenticated;
REVOKE UPDATE (pin_hash) ON public.profiles FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public.pin_trusted_devices (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id          UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  device_id_hash      TEXT NOT NULL,
  first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_user_agent     TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (profile_id, device_id_hash)
);

CREATE INDEX IF NOT EXISTS idx_pin_trusted_devices_profile
  ON public.pin_trusted_devices (profile_id);

ALTER TABLE public.pin_trusted_devices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pin_devices_admin_all" ON public.pin_trusted_devices;
CREATE POLICY "pin_devices_admin_all" ON public.pin_trusted_devices
  FOR ALL TO authenticated
  USING (public.get_user_role() = 'admin')
  WITH CHECK (public.get_user_role() = 'admin');

DROP POLICY IF EXISTS "pin_devices_own_select" ON public.pin_trusted_devices;
CREATE POLICY "pin_devices_own_select" ON public.pin_trusted_devices
  FOR SELECT TO authenticated
  USING (profile_id = auth.uid());
