-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 021 — Team PINs for field login
-- Depends on: 010_pin_auth_operational_users.sql
-- Purpose:
--   Replace per-user login-code/PIN with a shared 6-digit team PIN.
--   Each team color (rot, gruen, blau, gelb) gets one PIN hash.
--   Field login flow: enter PIN → see team members → pick yourself.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.team_pins (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  team_color  TEXT        NOT NULL UNIQUE,
  pin_hash    TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.team_pins IS
  'One PBKDF2-hashed 6-digit PIN per team color. Managed by admin only.';
COMMENT ON COLUMN public.team_pins.pin_hash IS
  'PBKDF2-SHA256 hash generated by the team-pin-login Edge Function. Never expose.';

ALTER TABLE public.team_pins ENABLE ROW LEVEL SECURITY;

-- Only admins (via service role in Edge Functions) can touch this table.
-- No direct authenticated access.
DROP POLICY IF EXISTS "team_pins_admin_all" ON public.team_pins;
CREATE POLICY "team_pins_admin_all" ON public.team_pins
  FOR ALL TO authenticated
  USING  (public.get_user_role() = 'admin')
  WITH CHECK (public.get_user_role() = 'admin');

-- Drop the old unique index on pin_login_code (no longer the lookup key).
-- The column stays so existing data is not destroyed; it can be cleared later.
-- DO NOT drop the column here — safe to leave nullable and ignored.
